name: CI on SDK 3.1.0

on:
  push:
    tags:
      # '**' also matches the slash ('/'), in contrast to '*',
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**'
  pull_request:
    branches:
      - main
  # Allows to run this workflow manually from the Actions tab.
  workflow_dispatch:

defaults:
  run:
    # Note that 'bash' provides -o pipefail, in contrast to the default (i.e. unspecified, which also uses bash) or 'sh',
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: sh

# Do not use concurrency in order to enforce checking every commit of a Pull Request.
# See, e.g.: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
#concurrency:
  #group: ci-${{ github.ref_name }}
  # 'false' (default) allows for two concurrent runs, one executing and one freshly enqueued; 'true' for only one; no 'concurrency:' defined for multiple.
  #cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      # Do not wait up to the default of 10 minutes for network timeouts in a workflow which runs ca. 2 minutes.
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Caching Docker images is not ready yet, see 
    # https://github.com/storeman-developers/harbour-storeman-installer/blob/devel/cache-docker-images_github-ci.md
    #- name: Cache Docker images of the Sailfish-SDK
    #  id: cache-sdk
    #  uses: actions/cache@v3
    #  with:
    #    path: $GITHUB_WORKSPACE/…
    #    key: cache

    - name: Prepare
      run: mkdir RPMS

    - name: Build i486 on 3.1.0.12
      uses: coderus/github-sfos-build@old-stable
      with:
        # Solely build for i486 on 3.1.0, because this is a noarch RPM and i486 matches the architecture of the host (compiling faster than cross-compilation)
        # and 3.1.0 is the oldest supported release hence with the smallest Docker image to download from Docker hub.
        # See also https://github.com/sailfishos-patches/patchmanager/pull/437#issuecomment-1615317003
        release: 3.1.0.12
        arch: i486

    - name: Upload build result
      uses: actions/upload-artifact@v3
      with:
        name: RPM-build-results
        path: RPMS/

